name: minimize_app
description: A flutter plugin to minimize the app
version: 1.0.0
homepage: https://github.com/Vanethos/minimize_app_plugin

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: de.eyev.minimize_app
        pluginClass: MinimizeAppPlugin
      ios:
        pluginClass: MinimizeAppPlugin
